#  server:
#  port:

spring:
  application:
    name: product-data-service

  datasource:
    url: jdbc:mysql://localhost:3306/mjym_user?characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  typeAliasesPackage: cn.how2j.springcloud.pojo
  mapperLocations: classpath:mapper/*.xml
